### ISSUE TITLE
Ignored pinned tabs not working

### ISSUE THREAD

**Issue by GM-Alex** [MrViolets/Tably#28]
If I enable ignore pinned tabs, open a new tab from a pinned tab, the pinned tabbed will be not longer be pinned and grouped. My expectation would be that the tab remains pinned and the new tab opens without a group. If I will open a second tab from the pinned tab a new group should be created with the new tab and the existing one. Now there should be the pinned tab and a group with the two tabs.

**Comment by MrViolets** [comment]
Thanks for reporting @GM-Alex 

This is fixed in the latest version.

**Comment by GM-Alex** [comment]
@MrViolets Works now flawlessly. Thanks a lot and I wish you happy holidays.
